# Generated by Django 2.2.1 on 2019-06-02 16:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190524_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 2, 16, 28, 35, 827778, tzinfo=utc)),
        ),
    ]
